#!/bin/sh

# prompt search
echo "" | 
dmenu -i -p "🔎 Search" |
# url encode spaces
sed 's/ /+/g' | 
# curl down the yotube search page
xargs -I{} curl -L "https://youtube.com/results?search_query={}" |
# extract the initial data and manipulate it to json
sed -n '/var ytInitialData/,/};/p' |
head -n 1 |
sed -e 's/.*var ytInitialData = \(.*}\);.*/\1/' > /tmp/yts-search.json && 
cat /tmp/yts-search.json |
# the JSON from youtube contains a bunch of things we don't need so just remove those 
simplify-youtube-json |
# take the json and make some li elements to show in webmenu
youtube-json-renderer | 
# prompt the webmenu
xargs -0 -I{} webmenu -s '{}' |
# show the result in mpv
xargs -I{} mpv --ytdl-format="bestvideo[height<=?720][fps<=?30][ext=webm]+bestaudio/best" "{}"


