name: "publish"
on:
  push:
    branches:
      - master

jobs:
  publish-webmenu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Load the binary to release
        id: release
        uses: ./.github/actions/release/
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
