name: "publish"
on:
  push:
    branches:
      - master

jobs:
  publish-webmenu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install
        run: yarn install

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load the binary to release
        id: release
        uses: ./.github/actions/release/
        with:
          tag_name: ${{ steps.semantic_release.outputs.new_release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
